/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LPk1ydkopdJ
 */
import React from "react";
import i18n from "@dhis2/d2-i18n";
import {
  CheckCheckIcon,
  FileIcon,
  MoreHorizontalIcon,
  MinusCircleIcon,
  HardHatIcon,
} from "lucide-react";
import { Button } from "../../ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "../../ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "../../ui/table"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "../../ui/dropdown-menu"
import {AddEnrollmentPageConfig} from "./AddEnrollmentPageConfig";
import {Tooltip, TooltipContent, TooltipProvider, TooltipTrigger} from "../../ui/tooltip";

export const EnrollmentOverview = () => {
  if (true) {
    return (
        <div className={'w-3/4 mt-4 flex flex-col text-center gap-4 text-gray-800 border mx-auto sm:mt-0 sm:w-1/3 px-4 py-6'}>
          <HardHatIcon className="h-8 w-8 text-gray-500 mx-auto"/>
          <p className={'text-xl italic'}>{i18n.t('Under construction')}</p>
          <p>{i18n.t('Come back very soon to try out enrollment plugins!')}</p>
        </div>
    )
  }

  return (
      <main className="grid flex-1 items-start gap-2 p-4 sm:px-6 sm:py-0 md:gap-4">
        <div className="w-full flex">
          <div className="ml-auto flex items-center gap-2">
            <Button disabled className="h-8 gap-1" size="sm" variant="outline">
              <FileIcon className="h-3.5 w-3.5"/>
              <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">Export</span>
            </Button>
            <AddEnrollmentPageConfig />
          </div>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Enrollment Plugins</CardTitle>
            <CardDescription>Manage your enrollment page configurations</CardDescription>
          </CardHeader>
          <CardContent>
            <Table className={'rounded-md border'}>
              <TableHeader>
                <TableRow>
                  <TableHead className="hidden md:table-cell">{i18n.t('Program')}</TableHead>
                  <TableHead className={'text-center'}>{i18n.t('Dashboard')}</TableHead>
                  <TableHead className={'text-center'}>{i18n.t('New event')}</TableHead>
                  <TableHead className={'text-center'}>{i18n.t('Edit event')}</TableHead>
                  <TableHead>
                    <span className="sr-only">{i18n.t('Actions')}</span>
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="hidden md:table-cell">Child Programme</TableCell>

                  <TableCell align={'center'} className={''} >
                    <CheckCheckIcon className="h-4 w-4"/>
                  </TableCell>

                  <TableCell align={'center'} className={''} >
                    <CheckCheckIcon className="h-4 w-4"/>
                  </TableCell>

                  <TableCell align={'center'} className={''} >
                    <TooltipProvider>
                      <Tooltip delayDuration={200}>
                        <TooltipTrigger>
                          <MinusCircleIcon className="h-4 w-4"/>
                        </TooltipTrigger>
                        <TooltipContent side="top">
                          {i18n.t('You are using the default configuration for this page')}
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </TableCell>

                  <TableCell align={'right'}>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button aria-haspopup="true" size="icon" variant="ghost">
                          <MoreHorizontalIcon className="h-4 w-4"/>
                          <span className="sr-only">Toggle menu</span>
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuLabel>Actions</DropdownMenuLabel>
                        <DropdownMenuItem>Edit</DropdownMenuItem>
                        <DropdownMenuItem>Delete</DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
          <CardFooter>
            <div className="text-xs text-muted-foreground">
              Showing
              <strong>1-10</strong> of <strong>10 </strong>
              products
            </div>
          </CardFooter>
        </Card>
      </main>
  )
}
